### ISSUE TITLE
Some inquiries

### ISSUE THREAD

**Issue by wakafa1** [h907308901/bawm#1]
# _Some inquiries_
I'm wakafa, I'm quite interested in your project. However, some parts of your source is beyond me, so I would like to ask some questions, I beg your return.   
1. What's your GIT developmental environment and OS?  
2. How can you employ so many sophisticaed Win32_API ? As far as i'm concerned, such functions are pretty easy to forget, did you refer to some related books or documents on the Internet ?  
3. With respect to __source file__, what's the procedure of packaging some other files into __.res__ (and of course __.rc__) and link them into your executeable file ? Did you do it with shell or with tools provided by IDE ?  

Thank you for reading.

**Comment by imhcyx** [comment]
1.I am using Windows 10 and Visual Studio 2015.
2.It does take time to memorize these APIs. I remember quite a few of them because I have made a number of Windows-based small programs. I do forget them sometimes, and then I refer to something like MSDN.
3.Visual Studio can do that while conpiling and linking, as long as you have added the files to the .rc file.
I don't know if I have answered your questions as you desired. Any further questions are welcome.

**Comment by wakafa1** [comment]
Much inspiration. Thank you!

**Comment by wakafa1** [comment]
By the way, how can you create the file 'output.txt'(which contains many numbers)?

**Comment by imhcyx** [comment]
The original file which consists of all printable characters is from the Internet. I converted it to this version.

**Comment by wakafa1** [comment]
Thank you for your patience. Have a good day.

**Comment by imhcyx** [comment]
You are welcome. The same to you!
